FROM --platform=linux/amd64 rocker/shiny-verse:latest

# System libraries
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    libgrpc++-dev \
    libprotobuf-dev \
    protobuf-compiler-grpc \
    pkg-config \
    && apt-get clean && rm -rf /var/lib/apt/lists/

# Install R packages
RUN R -e "install.packages(c('shinydashboard', 'shinydashboardPlus', 'shinythemes', 'reactable', 'bslib', 'shinycssloaders', 'httr', 'jsonlite', 'bigrquery', 'DBI', 'plotly', 'glue', 'here', 'ggthemes', 'scales', 'pool', 'bigrquerystorage', 'googleCloudStorageR'), repos='https://cran.rstudio.com/')"

# Create a directory for your shared scripts
RUN mkdir -p /srv/shiny-server/scripts
RUN mkdir -p /srv/shiny-server/sql

# Copy the app code (from the shiny folder)
COPY shiny/app.R /srv/shiny-server/
COPY scripts/run_sql.R /srv/shiny-server/scripts/
COPY sql/ /srv/shiny-server/sql
COPY shiny/www /srv/shiny-server/wwww

COPY .here /srv/shiny-server/.here

# Set permissions for the shiny user
RUN chown -R shiny:shiny /srv/shiny-server

# Cloud Run uses port 8080 by default
EXPOSE 8080

# This command overrides the default config to listen on the correct port
CMD ["R", "-e", "shiny::runApp('/srv/shiny-server/app.R', host = '0.0.0.0', port = 8080)"]