# This is the Docker Container for the yt_sailing_channel_etl_job

# Base R image
FROM --platform=linux/amd64 rocker/tidyverse

# Install R Dependencies
RUN R -e "install.packages('httr')"
RUN R -e "install.packages('jsonlite')"
RUN R -e "install.packages('dplyr')"
RUN R -e "install.packages('bigrquery')"
RUN R -e "install.packages('gargle')"
RUN R -e "install.packages('DBI')"

# Copy over necessary files
COPY .config/gcloud/yt-sailing-dashboard-1a37e4c18a27.json .config/gcloud/yt-sailing-dashboard-1a37e4c18a27.json

# Copy the script over
COPY collect_data_by_handle.R collect_data_by_handle.R

# Run the R script
CMD R -e "source('collect_data_by_handle.R')"