# This is the Docker Container for the yt_sailing_channel_etl_job

# Base R image
FROM --platform=linux/amd64 rocker/tidyverse

# Install R Dependencies
RUN R -e "install.packages(c('httr', 'jsonlite', 'dplyr', 'bigrquery', 'gargle', 'DBI', 'glue'))"

# Create directories
RUN mkdir -p /app/scripts
RUN mkdir -p /app/sql


# Copy the ETL specific code
COPY etl/main_etl.R /app/

# Copy the SHARED functions
COPY scripts/ /app/scripts/
COPY sql/ /app/sql/

COPY .here /app/.here

# Set working directory
WORKDIR /app

CMD ["Rscript", "main_etl.R"]