# This is the Docker Container for the yt_sailing_channel_etl_job

# Base R image
FROM --platform=linux/amd64 rocker/tidyverse

# Install R Dependencies
RUN R -e "install.packages(c('httr', 'jsonlite', 'dplyr', 'bigrquery', 'gargle',
                             'DBI', 'glue'))"

# Create directories
RUN mkdir -p /app/scripts

# Copy the ETL specific code
COPY etl/main_etl.R /app/

# Copy the SHARED functions
COPY scripts/run_sql.R /app/scripts/

# Set working directory
WORKDIR /app

CMD ["Rscript", "main_etl.R"]